### ISSUE TITLE
logging AlbyResponseError does not show error message

### ISSUE THREAD

**Issue by rolznz** [getAlby/alby-js-sdk#25]
![image](https://github.com/getAlby/alby-js-sdk/assets/33993199/39fe1a01-0130-4823-b313-690add7952b8)

**Comment by bumi** [comment]
how did you get that error?

**Comment by rolznz** [comment]
Sending a payment in regtest. Maybe related to @kiwiidb's testing?

But this error will always be thrown if the status of a request has a non-ok status code

**Comment by rolznz** [comment]
The AlbyResponseError class extends Error but does not set the `message` field. I think if we do this then the issue should be fixed.
