### ISSUE TITLE
Importing types are a bit strange / auto-suggests to import from dist folder

### ISSUE THREAD

**Issue by rolznz** [getAlby/alby-js-sdk#32]
Currently you have to do this, which is auto-suggested by the IDE:
```
import { Invoice, Token } from "alby-js-sdk/dist/types";
```
or
```
import { types } from "alby-js-sdk";
// invoice available as types.Invoice
```

Ideally you would just do:
```
import { Invoice } from "alby-js-sdk/types";
```

**Comment by bumi** [comment]
is that a problem? I think the dist folder is in the npm package. we would need to change this to root. 
https://www.npmjs.com/package/alby-js-sdk?activeTab=code

**Comment by rolznz** [comment]
@bumi I am not sure how to fix this. I think it makes sense to have a dist folder, compiling inline sucks. So maybe we just keep it as is
